package com.structure.data.model;
// Generated Dec 1, 2018 6:03:33 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TmguruId generated by hbm2java
 */
@Embeddable
public class TmguruId implements java.io.Serializable {

	private String idGuru;
	private int nip;

	public TmguruId() {
	}

	public TmguruId(String idGuru, int nip) {
		this.idGuru = idGuru;
		this.nip = nip;
	}

	@Column(name = "ID_GURU", nullable = false, length = 10)
	public String getIdGuru() {
		return this.idGuru;
	}

	public void setIdGuru(String idGuru) {
		this.idGuru = idGuru;
	}

	@Column(name = "NIP", nullable = false)
	public int getNip() {
		return this.nip;
	}

	public void setNip(int nip) {
		this.nip = nip;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmguruId))
			return false;
		TmguruId castOther = (TmguruId) other;

		return ((this.getIdGuru() == castOther.getIdGuru()) || (this.getIdGuru() != null
				&& castOther.getIdGuru() != null && this.getIdGuru().equals(castOther.getIdGuru())))
				&& (this.getNip() == castOther.getNip());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdGuru() == null ? 0 : this.getIdGuru().hashCode());
		result = 37 * result + this.getNip();
		return result;
	}

}
