package com.structure.data.model;
// Generated Dec 1, 2018 6:03:33 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tmsekolah generated by hbm2java
 */
@Entity
@Table(name = "tmsekolah", catalog = "sdn_pasirkaliki")
public class Tmsekolah implements java.io.Serializable {

	private int idSekolah;
	private String namaSekolah;
	private String alamat;
	private Date tglBerdiri;
	private String createdBy;
	private Date createdDt;
	private String modifiedBy;
	private Date modifiedDt;

	public Tmsekolah() {
	}

	public Tmsekolah(int idSekolah) {
		this.idSekolah = idSekolah;
	}

	public Tmsekolah(int idSekolah, String namaSekolah, String alamat, Date tglBerdiri, String createdBy,
			Date createdDt, String modifiedBy, Date modifiedDt) {
		this.idSekolah = idSekolah;
		this.namaSekolah = namaSekolah;
		this.alamat = alamat;
		this.tglBerdiri = tglBerdiri;
		this.createdBy = createdBy;
		this.createdDt = createdDt;
		this.modifiedBy = modifiedBy;
		this.modifiedDt = modifiedDt;
	}

	@Id

	@Column(name = "ID_SEKOLAH", unique = true, nullable = false)
	public int getIdSekolah() {
		return this.idSekolah;
	}

	public void setIdSekolah(int idSekolah) {
		this.idSekolah = idSekolah;
	}

	@Column(name = "NAMA_SEKOLAH", length = 20)
	public String getNamaSekolah() {
		return this.namaSekolah;
	}

	public void setNamaSekolah(String namaSekolah) {
		this.namaSekolah = namaSekolah;
	}

	@Column(name = "ALAMAT", length = 50)
	public String getAlamat() {
		return this.alamat;
	}

	public void setAlamat(String alamat) {
		this.alamat = alamat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TGL_BERDIRI", length = 10)
	public Date getTglBerdiri() {
		return this.tglBerdiri;
	}

	public void setTglBerdiri(Date tglBerdiri) {
		this.tglBerdiri = tglBerdiri;
	}

	@Column(name = "CREATED_BY", length = 30)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DT", length = 19)
	public Date getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	@Column(name = "MODIFIED_BY", length = 30)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFIED_DT", length = 19)
	public Date getModifiedDt() {
		return this.modifiedDt;
	}

	public void setModifiedDt(Date modifiedDt) {
		this.modifiedDt = modifiedDt;
	}

}
