package com.structure.data.model;
// Generated Dec 8, 2018 2:09:31 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tmsiswa generated by hbm2java
 */
@Entity
@Table(name = "tmsiswa", catalog = "sdn_pasirkaliki")
public class Tmsiswa implements java.io.Serializable {

	private TmsiswaId id;
	private String nama;
	private String jenisKelamin;
	private String tempatLahir;
	private Date tglLahir;
	private String agama;
	private String alamat;
	private String kelas;
	private String createdBy;
	private Date createdDt;
	private String modifiedBy;
	private Date modifiedDt;
	private String asalSekolah;
	private String status;

	public Tmsiswa() {
	}

	public Tmsiswa(TmsiswaId id, String status) {
		this.id = id;
		this.status = status;
	}

	public Tmsiswa(TmsiswaId id, String nama, String jenisKelamin, String tempatLahir, Date tglLahir, String agama,
			String alamat, String kelas, String createdBy, Date createdDt, String modifiedBy, Date modifiedDt,
			String asalSekolah, String status) {
		this.id = id;
		this.nama = nama;
		this.jenisKelamin = jenisKelamin;
		this.tempatLahir = tempatLahir;
		this.tglLahir = tglLahir;
		this.agama = agama;
		this.alamat = alamat;
		this.kelas = kelas;
		this.createdBy = createdBy;
		this.createdDt = createdDt;
		this.modifiedBy = modifiedBy;
		this.modifiedDt = modifiedDt;
		this.asalSekolah = asalSekolah;
		this.status = status;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "nis", column = @Column(name = "NIS", nullable = false, length = 9)),
			@AttributeOverride(name = "nisn", column = @Column(name = "NISN", nullable = false, length = 10)) })
	public TmsiswaId getId() {
		return this.id;
	}

	public void setId(TmsiswaId id) {
		this.id = id;
	}

	@Column(name = "NAMA", length = 30)
	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	@Column(name = "JENIS_KELAMIN", length = 1)
	public String getJenisKelamin() {
		return this.jenisKelamin;
	}

	public void setJenisKelamin(String jenisKelamin) {
		this.jenisKelamin = jenisKelamin;
	}

	@Column(name = "TEMPAT_LAHIR", length = 20)
	public String getTempatLahir() {
		return this.tempatLahir;
	}

	public void setTempatLahir(String tempatLahir) {
		this.tempatLahir = tempatLahir;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TGL_LAHIR", length = 10)
	public Date getTglLahir() {
		return this.tglLahir;
	}

	public void setTglLahir(Date tglLahir) {
		this.tglLahir = tglLahir;
	}

	@Column(name = "AGAMA", length = 20)
	public String getAgama() {
		return this.agama;
	}

	public void setAgama(String agama) {
		this.agama = agama;
	}

	@Column(name = "ALAMAT", length = 50)
	public String getAlamat() {
		return this.alamat;
	}

	public void setAlamat(String alamat) {
		this.alamat = alamat;
	}

	@Column(name = "KELAS", length = 5)
	public String getKelas() {
		return this.kelas;
	}

	public void setKelas(String kelas) {
		this.kelas = kelas;
	}

	@Column(name = "CREATED_BY", length = 30)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DT", length = 19)
	public Date getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	@Column(name = "MODIFIED_BY", length = 30)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFIED_DT", length = 19)
	public Date getModifiedDt() {
		return this.modifiedDt;
	}

	public void setModifiedDt(Date modifiedDt) {
		this.modifiedDt = modifiedDt;
	}

	@Column(name = "ASAL_SEKOLAH", length = 50)
	public String getAsalSekolah() {
		return this.asalSekolah;
	}

	public void setAsalSekolah(String asalSekolah) {
		this.asalSekolah = asalSekolah;
	}

	@Column(name = "STATUS", nullable = false, length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
