package com.structure.data.model;
// Generated Dec 1, 2018 6:03:33 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TmsiswaId generated by hbm2java
 */
@Embeddable
public class TmsiswaId implements java.io.Serializable {

	private String nis;
	private String nisn;

	public TmsiswaId() {
	}

	public TmsiswaId(String nis, String nisn) {
		this.nis = nis;
		this.nisn = nisn;
	}

	@Column(name = "NIS", nullable = false, length = 9)
	public String getNis() {
		return this.nis;
	}

	public void setNis(String nis) {
		this.nis = nis;
	}

	@Column(name = "NISN", nullable = false, length = 10)
	public String getNisn() {
		return this.nisn;
	}

	public void setNisn(String nisn) {
		this.nisn = nisn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmsiswaId))
			return false;
		TmsiswaId castOther = (TmsiswaId) other;

		return ((this.getNis() == castOther.getNis())
				|| (this.getNis() != null && castOther.getNis() != null && this.getNis().equals(castOther.getNis())))
				&& ((this.getNisn() == castOther.getNisn()) || (this.getNisn() != null && castOther.getNisn() != null
						&& this.getNisn().equals(castOther.getNisn())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNis() == null ? 0 : this.getNis().hashCode());
		result = 37 * result + (getNisn() == null ? 0 : this.getNisn().hashCode());
		return result;
	}

}
