package com.structure.data.model;
// Generated Dec 8, 2018 2:09:31 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ttsiswahistory generated by hbm2java
 */
@Entity
@Table(name = "ttsiswahistory", catalog = "sdn_pasirkaliki")
public class Ttsiswahistory implements java.io.Serializable {

	private Integer orderNo;
	private Integer nis;
	private Integer nisn;
	private String status;
	private String kelas;
	private String createdBy;
	private Date createdDt;
	private String modifiedBy;
	private Date modifiedDt;

	public Ttsiswahistory() {
	}

	public Ttsiswahistory(Integer nis, Integer nisn, String status, String kelas, String createdBy, Date createdDt,
			String modifiedBy, Date modifiedDt) {
		this.nis = nis;
		this.nisn = nisn;
		this.status = status;
		this.kelas = kelas;
		this.createdBy = createdBy;
		this.createdDt = createdDt;
		this.modifiedBy = modifiedBy;
		this.modifiedDt = modifiedDt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ORDER_NO", unique = true, nullable = false)
	public Integer getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(Integer orderNo) {
		this.orderNo = orderNo;
	}

	@Column(name = "NIS")
	public Integer getNis() {
		return this.nis;
	}

	public void setNis(Integer nis) {
		this.nis = nis;
	}

	@Column(name = "NISN")
	public Integer getNisn() {
		return this.nisn;
	}

	public void setNisn(Integer nisn) {
		this.nisn = nisn;
	}

	@Column(name = "STATUS", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "KELAS", length = 5)
	public String getKelas() {
		return this.kelas;
	}

	public void setKelas(String kelas) {
		this.kelas = kelas;
	}

	@Column(name = "CREATED_BY", length = 30)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DT", length = 19)
	public Date getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	@Column(name = "MODIFIED_BY", length = 30)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFIED_DT", length = 19)
	public Date getModifiedDt() {
		return this.modifiedDt;
	}

	public void setModifiedDt(Date modifiedDt) {
		this.modifiedDt = modifiedDt;
	}

}
